apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-access-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
